name: Publish Pre-Release Package

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create Release Zip Archive
      id: zip_release
      run: |
        # 使用 GitHub Actions 提供的内置工具进行压缩
        zip -r releasetest.zip 圆转方拓展包\ For\ Java\ Edition/

    - name: Create Pre-Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: pre-${{ github.sha }}
        release_name: Pre-release version for commit ${{ github.sha }}
        draft: false
        prerelease: true
        files: releasetest.zip
